import { WaitlistEntry, AdminStats } from './types';

export const MOCK_ENTRIES: WaitlistEntry[] = [
  {
    id: 'entry-001',
    email: 'ahmed.hassan@gmail.com',
    phone: null,
    firstName: 'Ahmed',
    category: 'YouTube / Content Creator',
    audienceSize: '10,000–50,000',
    monetizationMethods: ['Ads', 'Sponsorships'],
    paymentMethods: ['Vodafone Cash', 'Bank transfer'],
    recurringPaymentProblems: ['Customers forget to renew', 'I have to manually verify payments'],
    intendedUse: 'Exclusive content',
    creatorMembershipExperience: 'No',
    creatorMembershipPlatform: null,
    openEndedResponse: 'I want a simple way to offer monthly exclusive content to my subscribers without manually tracking payments every month.',
    questionnaireStarted: true,
    questionnaireCompleted: true,
    questionnaireSkipped: false,
    utmSource: 'instagram',
    utmMedium: 'paid_social',
    utmCampaign: 'creators_aug2026',
    utmContent: 'reel_v1',
    referrer: 'https://instagram.com',
    source: 'Instagram',
    createdAt: '2026-08-24T10:23:00Z',
    updatedAt: '2026-08-24T10:28:00Z',
  },
  {
    id: 'entry-002',
    email: null,
    phone: '+201012345678',
    firstName: 'Nour',
    category: 'Coach / Consultant',
    audienceSize: null,
    monetizationMethods: ['Selling services', 'Subscriptions handled manually'],
    paymentMethods: ['InstaPay', 'Bank transfer'],
    recurringPaymentProblems: ['I manually give/remove access', 'Managing subscribers is messy'],
    intendedUse: 'Coaching',
    creatorMembershipExperience: null,
    creatorMembershipPlatform: null,
    openEndedResponse: 'I need a way to automatically manage my coaching clients — right now I track everything in spreadsheets.',
    questionnaireStarted: true,
    questionnaireCompleted: true,
    questionnaireSkipped: false,
    utmSource: 'instagram',
    utmMedium: 'paid_social',
    utmCampaign: 'coaches_aug2026',
    utmContent: 'story_v2',
    referrer: 'https://instagram.com',
    source: 'Instagram',
    createdAt: '2026-08-24T11:05:00Z',
    updatedAt: '2026-08-24T11:12:00Z',
  },
  {
    id: 'entry-003',
    email: 'omar.creator@outlook.com',
    phone: null,
    firstName: 'Omar',
    category: 'Streamer / Gamer',
    audienceSize: '1,000–10,000',
    monetizationMethods: ['Donations / tips', 'Ads'],
    paymentMethods: ['Vodafone Cash', 'Cash'],
    recurringPaymentProblems: ['I don\'t have a way to offer subscriptions', 'Customers ask for local payment methods'],
    intendedUse: 'Paid memberships',
    creatorMembershipExperience: "I'm considering it",
    creatorMembershipPlatform: null,
    openEndedResponse: '',
    questionnaireStarted: true,
    questionnaireCompleted: true,
    questionnaireSkipped: false,
    utmSource: 'facebook',
    utmMedium: 'paid_social',
    utmCampaign: 'gamers_aug2026',
    utmContent: null,
    referrer: 'https://facebook.com',
    source: 'Facebook',
    createdAt: '2026-08-24T12:30:00Z',
    updatedAt: '2026-08-24T12:35:00Z',
  },
  {
    id: 'entry-004',
    email: 'sara.educator@gmail.com',
    phone: '+201156789012',
    firstName: 'Sara',
    category: 'Educator / Course Creator',
    audienceSize: '50,000–100,000',
    monetizationMethods: ['Selling courses', 'Selling digital products'],
    paymentMethods: ['Bank card', 'Fawry'],
    recurringPaymentProblems: ['Payment fees', 'International payment methods are difficult'],
    intendedUse: 'Courses',
    creatorMembershipExperience: 'Yes',
    creatorMembershipPlatform: 'Patreon',
    openEndedResponse: 'I currently use Patreon but it\'s hard to explain to Egyptian students. I need something local.',
    questionnaireStarted: true,
    questionnaireCompleted: true,
    questionnaireSkipped: false,
    utmSource: 'instagram',
    utmMedium: 'organic',
    utmCampaign: null,
    utmContent: null,
    referrer: 'https://instagram.com',
    source: 'Instagram',
    createdAt: '2026-08-24T13:45:00Z',
    updatedAt: '2026-08-24T13:52:00Z',
  },
  {
    id: 'entry-005',
    email: 'karim.podcast@gmail.com',
    phone: null,
    firstName: 'Karim',
    category: 'Podcaster',
    audienceSize: '1,000–10,000',
    monetizationMethods: ['Sponsorships', 'I don\'t monetize yet'],
    paymentMethods: ['I don\'t currently have paying customers'],
    recurringPaymentProblems: ['I don\'t have a way to offer subscriptions'],
    intendedUse: 'Exclusive content',
    creatorMembershipExperience: 'No',
    creatorMembershipPlatform: null,
    openEndedResponse: 'I want to offer a paid tier for my podcast listeners with bonus episodes.',
    questionnaireStarted: true,
    questionnaireCompleted: false,
    questionnaireSkipped: false,
    utmSource: 'direct',
    utmMedium: null,
    utmCampaign: null,
    utmContent: null,
    referrer: null,
    source: 'Direct',
    createdAt: '2026-08-24T14:20:00Z',
    updatedAt: '2026-08-24T14:22:00Z',
  },
  {
    id: 'entry-006',
    email: 'mona.freelancer@hotmail.com',
    phone: null,
    firstName: 'Mona',
    category: 'Freelancer / Service Provider',
    audienceSize: null,
    monetizationMethods: ['Selling services'],
    paymentMethods: ['Bank transfer', 'InstaPay'],
    recurringPaymentProblems: ['I have to manually verify payments', 'Managing subscribers is messy'],
    intendedUse: 'Recurring services',
    creatorMembershipExperience: null,
    creatorMembershipPlatform: null,
    openEndedResponse: 'I do monthly social media management and I need clients to pay automatically.',
    questionnaireStarted: true,
    questionnaireCompleted: true,
    questionnaireSkipped: false,
    utmSource: 'linkedin',
    utmMedium: 'organic',
    utmCampaign: null,
    utmContent: null,
    referrer: 'https://linkedin.com',
    source: 'LinkedIn',
    createdAt: '2026-08-24T15:10:00Z',
    updatedAt: '2026-08-24T15:18:00Z',
  },
  {
    id: 'entry-007',
    email: 'youssef.digital@gmail.com',
    phone: '+201234567890',
    firstName: 'Youssef',
    category: 'Digital Product Seller',
    audienceSize: null,
    monetizationMethods: ['Selling digital products'],
    paymentMethods: ['Vodafone Cash', 'Bank card'],
    recurringPaymentProblems: ['I don\'t have a way to offer subscriptions', 'Payment fees'],
    intendedUse: 'Digital products',
    creatorMembershipExperience: null,
    creatorMembershipPlatform: null,
    openEndedResponse: '',
    questionnaireStarted: true,
    questionnaireCompleted: true,
    questionnaireSkipped: false,
    utmSource: 'instagram',
    utmMedium: 'paid_social',
    utmCampaign: 'creators_aug2026',
    utmContent: 'reel_v1',
    referrer: 'https://instagram.com',
    source: 'Instagram',
    createdAt: '2026-08-24T16:00:00Z',
    updatedAt: '2026-08-24T16:07:00Z',
  },
  {
    id: 'entry-008',
    email: 'layla.community@gmail.com',
    phone: null,
    firstName: 'Layla',
    category: 'Community Owner',
    audienceSize: '10,000–50,000',
    monetizationMethods: ['Paid memberships', 'Donations / tips'],
    paymentMethods: ['Vodafone Cash', 'Multiple methods'],
    recurringPaymentProblems: ['Customers forget to renew', 'I manually give/remove access'],
    intendedUse: 'Private community',
    creatorMembershipExperience: 'Yes',
    creatorMembershipPlatform: 'My own system',
    openEndedResponse: 'Managing a paid Telegram community manually is exhausting. I need automation.',
    questionnaireStarted: true,
    questionnaireCompleted: true,
    questionnaireSkipped: false,
    utmSource: 'instagram',
    utmMedium: 'paid_social',
    utmCampaign: 'community_aug2026',
    utmContent: 'story_v1',
    referrer: 'https://instagram.com',
    source: 'Instagram',
    createdAt: '2026-08-25T08:15:00Z',
    updatedAt: '2026-08-25T08:22:00Z',
  },
  {
    id: 'entry-009',
    email: 'hana.business@gmail.com',
    phone: null,
    firstName: 'Hana',
    category: 'Small Business',
    audienceSize: null,
    monetizationMethods: ['Selling services', 'Subscriptions handled manually'],
    paymentMethods: ['Cash', 'Bank transfer', 'Vodafone Cash'],
    recurringPaymentProblems: ['Customers forget to renew', 'I have to manually verify payments'],
    intendedUse: 'Recurring services',
    creatorMembershipExperience: null,
    creatorMembershipPlatform: null,
    openEndedResponse: 'I run a small gym and managing monthly membership payments is a nightmare.',
    questionnaireStarted: true,
    questionnaireCompleted: true,
    questionnaireSkipped: false,
    utmSource: 'facebook',
    utmMedium: 'paid_social',
    utmCampaign: 'business_aug2026',
    utmContent: null,
    referrer: 'https://facebook.com',
    source: 'Facebook',
    createdAt: '2026-08-25T09:30:00Z',
    updatedAt: '2026-08-25T09:38:00Z',
  },
  {
    id: 'entry-010',
    email: 'tarek.coach@gmail.com',
    phone: '+201512345678',
    firstName: 'Tarek',
    category: 'Coach / Consultant',
    audienceSize: null,
    monetizationMethods: ['Selling services'],
    paymentMethods: ['InstaPay', 'Vodafone Cash'],
    recurringPaymentProblems: ['I manually give/remove access', 'Managing subscribers is messy'],
    intendedUse: 'Coaching',
    creatorMembershipExperience: null,
    creatorMembershipPlatform: null,
    openEndedResponse: 'I need a professional way to sell monthly coaching packages.',
    questionnaireStarted: false,
    questionnaireCompleted: false,
    questionnaireSkipped: true,
    utmSource: 'instagram',
    utmMedium: 'paid_social',
    utmCampaign: 'coaches_aug2026',
    utmContent: 'reel_v2',
    referrer: 'https://instagram.com',
    source: 'Instagram',
    createdAt: '2026-08-25T10:05:00Z',
    updatedAt: '2026-08-25T10:05:00Z',
  },
  {
    id: 'entry-011',
    email: 'dina.youtuber@gmail.com',
    phone: null,
    firstName: 'Dina',
    category: 'YouTube / Content Creator',
    audienceSize: '100,000–500,000',
    monetizationMethods: ['Ads', 'Sponsorships', 'Paid memberships'],
    paymentMethods: ['YouTube Memberships', 'Patreon'],
    recurringPaymentProblems: ['Customers ask for local payment methods', 'International payment methods are difficult'],
    intendedUse: 'Exclusive content',
    creatorMembershipExperience: 'Yes',
    creatorMembershipPlatform: 'YouTube Memberships',
    openEndedResponse: 'My Egyptian audience keeps asking for a way to support me locally. YouTube memberships don\'t work well for them.',
    questionnaireStarted: true,
    questionnaireCompleted: true,
    questionnaireSkipped: false,
    utmSource: 'instagram',
    utmMedium: 'paid_social',
    utmCampaign: 'creators_aug2026',
    utmContent: 'reel_v3',
    referrer: 'https://instagram.com',
    source: 'Instagram',
    createdAt: '2026-08-25T11:20:00Z',
    updatedAt: '2026-08-25T11:28:00Z',
  },
  {
    id: 'entry-012',
    email: 'mahmoud.other@gmail.com',
    phone: '+201198765432',
    firstName: 'Mahmoud',
    category: 'Other',
    audienceSize: null,
    monetizationMethods: ['Other'],
    paymentMethods: ['Bank transfer'],
    recurringPaymentProblems: ['I don\'t currently have this problem'],
    intendedUse: 'Something else',
    creatorMembershipExperience: null,
    creatorMembershipPlatform: null,
    openEndedResponse: 'I run an online subscription for a niche newsletter.',
    questionnaireStarted: true,
    questionnaireCompleted: true,
    questionnaireSkipped: false,
    utmSource: 'direct',
    utmMedium: null,
    utmCampaign: null,
    utmContent: null,
    referrer: null,
    source: 'Direct',
    createdAt: '2026-08-25T12:45:00Z',
    updatedAt: '2026-08-25T12:52:00Z',
  },
];

export const MOCK_STATS: AdminStats = {
  totalSignups: 12,
  newSignupsToday: 5,
  creatorSignups: 7,
  nonCreatorSignups: 5,
  questionnaireStarts: 11,
  questionnaireCompletions: 10,
  questionnaireSkips: 1,
  questionnaireAbandonment: 1,
  completionRate: 91,
  categoryBreakdown: [
    { category: 'YouTube / Content Creator', count: 2 },
    { category: 'Coach / Consultant', count: 2 },
    { category: 'Educator / Course Creator', count: 1 },
    { category: 'Streamer / Gamer', count: 1 },
    { category: 'Podcaster', count: 1 },
    { category: 'Community Owner', count: 1 },
    { category: 'Freelancer / Service Provider', count: 1 },
    { category: 'Digital Product Seller', count: 1 },
    { category: 'Small Business', count: 1 },
    { category: 'Other', count: 1 },
  ],
  sourceBreakdown: [
    { source: 'Instagram', count: 8 },
    { source: 'Facebook', count: 2 },
    { source: 'Direct', count: 1 },
    { source: 'LinkedIn', count: 1 },
  ],
  dailySignups: [
    { date: 'Aug 19', count: 0 },
    { date: 'Aug 20', count: 1 },
    { date: 'Aug 21', count: 0 },
    { date: 'Aug 22', count: 2 },
    { date: 'Aug 23', count: 1 },
    { date: 'Aug 24', count: 3 },
    { date: 'Aug 25', count: 5 },
  ],
  topProblems: [
    { problem: 'Customers forget to renew', count: 4 },
    { problem: 'Manual payment verification', count: 4 },
    { problem: 'Manual access management', count: 4 },
    { problem: 'No subscription offering', count: 3 },
    { problem: 'Managing subscribers', count: 3 },
    { problem: 'Local payment methods', count: 2 },
    { problem: 'Payment fees', count: 2 },
    { problem: 'International payments', count: 2 },
  ],
  paymentMethodBreakdown: [
    { method: 'Vodafone Cash', count: 6 },
    { method: 'Bank transfer', count: 5 },
    { method: 'InstaPay', count: 3 },
    { method: 'Bank card', count: 2 },
    { method: 'Cash', count: 2 },
    { method: 'Fawry', count: 1 },
  ],
};